# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 00:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveIntegration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(null=True)),
                ('external_user_id', models.TextField(null=True, verbose_name='Unique ID of User in External Service.')),
            ],
        ),
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('image_url', models.TextField(null=True)),
                ('auth_url', models.TextField(null=True)),
                ('token_url', models.TextField(null=True)),
                ('users', models.ManyToManyField(blank=True, through='eleos_core.ActiveIntegration', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('image_url', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('image_url', models.TextField(null=True)),
                ('length', models.DurationField(null=True, verbose_name='The expected length of time Payload will fill.')),
                ('deliverable', models.TextField(null=True)),
            ],
            options={
                'ordering': ['length'],
            },
        ),
        migrations.AddField(
            model_name='module',
            name='possible_payloads',
            field=models.ManyToManyField(blank=True, to='eleos_core.Payload'),
        ),
        migrations.AddField(
            model_name='module',
            name='required_integrations',
            field=models.ManyToManyField(blank=True, to='eleos_core.Integration'),
        ),
        migrations.AddField(
            model_name='module',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activeintegration',
            name='integration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eleos_core.Integration'),
        ),
        migrations.AddField(
            model_name='activeintegration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
