# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eleos_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='auth_url',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='integration',
            name='name',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userintegrationlink',
            name='integration',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='eleos_core.Integration'),
            preserve_default=False,
        ),
    ]
