# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleos_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeintegration',
            name='access_token',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='activeintegration',
            name='external_user_id',
            field=models.TextField(blank=True, default=None, verbose_name='Unique ID of User in External Service.'),
        ),
        migrations.AlterField(
            model_name='integration',
            name='auth_url',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='integration',
            name='description',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='integration',
            name='image_url',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='integration',
            name='token_url',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='module',
            name='image_url',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='payload',
            name='deliverable',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='payload',
            name='description',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='payload',
            name='image_url',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='payload',
            name='length',
            field=models.DurationField(blank=True, default=None, verbose_name='The expected length of time, in seconds, Payload will fill.'),
        ),
    ]
