# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleos_core', '0003_auto_20161214_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeintegration',
            name='access_token',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
