# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleos_core', '0003_auto_20161212_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('length', models.DurationField(null=True, verbose_name='The expected length of time Payload will fill.')),
                ('deliverable', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='userintegrationlink',
            name='auth_token',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='integration',
            name='auth_url',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='possible_payloads',
            field=models.ManyToManyField(to='eleos_core.Payload'),
        ),
        migrations.AddField(
            model_name='module',
            name='required_integrations',
            field=models.ManyToManyField(to='eleos_core.Integration'),
        ),
    ]
