# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleos_core', '0004_auto_20161212_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='possible_payloads',
            field=models.ManyToManyField(blank=True, to='eleos_core.Payload'),
        ),
        migrations.AlterField(
            model_name='module',
            name='required_integrations',
            field=models.ManyToManyField(blank=True, to='eleos_core.Integration'),
        ),
    ]
