# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 23:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eleos_core', '0005_auto_20161212_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userintegrationlink',
            name='integration',
        ),
        migrations.RemoveField(
            model_name='userintegrationlink',
            name='user',
        ),
        migrations.AddField(
            model_name='integration',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserIntegrationLink',
        ),
    ]
