# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleos_core', '0006_auto_20161222_0013'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthCredentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_token', models.TextField(blank=True, default=None, null=True)),
                ('request_token_secret', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
    ]
