# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 03:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eleos_core', '0007_auto_20161212_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='integration',
            name='image_url',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='image_url',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payload',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='payload',
            name='image_url',
            field=models.TextField(null=True),
        ),
    ]
