# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleos_core', '0007_oauthcredentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeintegration',
            name='access_token_secret',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
