# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleos_core', '0008_auto_20161213_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='token_url',
            field=models.TextField(null=True),
        ),
    ]
