# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 00:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eleos_core', '0008_activeintegration_access_token_secret'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftedMoment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endorsement', models.TextField(blank=True, default=None, null=True)),
                ('context', models.CharField(choices=[('PRD', 'Productivity'), ('ENT', 'Entertainment'), ('INS', 'Inspiration'), ('EDU', 'Education')], default='ENT', max_length=2)),
                ('creator', models.ManyToManyField(related_name='creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='payload',
            name='deliverable_url',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='giftedmoment',
            name='payload',
            field=models.ManyToManyField(to='eleos_core.Payload'),
        ),
        migrations.AddField(
            model_name='giftedmoment',
            name='recipient',
            field=models.ManyToManyField(related_name='recipient', to=settings.AUTH_USER_MODEL),
        ),
    ]
