# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleos_core', '0009_auto_20161227_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftedmoment',
            name='context',
            field=models.CharField(choices=[('PRD', 'Productivity'), ('ENT', 'Entertainment'), ('INS', 'Inspiration'), ('EDU', 'Education')], default='ENT', max_length=3),
        ),
    ]
