# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 01:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eleos_core', '0010_auto_20161227_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giftedmoment',
            name='creator',
        ),
        migrations.AddField(
            model_name='giftedmoment',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='giftedmoment',
            name='payload',
        ),
        migrations.AddField(
            model_name='giftedmoment',
            name='payload',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='eleos_core.Payload'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='giftedmoment',
            name='recipient',
        ),
        migrations.AddField(
            model_name='giftedmoment',
            name='recipient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
