# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleos_core', '0011_auto_20161227_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftedmoment',
            name='created_at',
            field=models.DateTimeField(default=None, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='giftedmoment',
            name='fbm_message_id',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='giftedmoment',
            name='fbm_message_read_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='giftedmoment',
            name='fbm_message_sent_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='giftedmoment',
            name='fbm_read_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='giftedmoment',
            name='updated_at',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
