# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleos_core', '0013_auto_20161227_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftedmoment',
            name='fbm_message_read_at',
            field=models.DateTimeField(default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='giftedmoment',
            name='fbm_message_sent_at',
            field=models.DateTimeField(default=None, editable=False, null=True),
        ),
    ]
