# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleos_core', '0014_auto_20161227_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftedmoment',
            name='fbm_sent_status',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
