# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleos_core', '0015_giftedmoment_fbm_sent_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftedmoment',
            name='fbm_payload_click_at',
            field=models.DateTimeField(default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='giftedmoment',
            name='fbm_payload_click_count',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='giftedmoment',
            name='fbm_payload_click_status',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
