# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 02:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eleos_core', '0017_auto_20170113_0230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payload',
            name='deliverable',
        ),
    ]
