# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleos_core', '0018_remove_payload_deliverable'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftedmoment',
            name='datetime_task_queued',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
