# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 06:57
from __future__ import unicode_literals

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('eleos_core', '0019_giftedmoment_datetime_task_queued'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftedmoment',
            name='deliver_time_zone',
            field=timezone_field.fields.TimeZoneField(blank=True, default='US/Pacific'),
        ),
    ]
