# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-04 04:44
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eleos_core', '0021_auto_20170113_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(blank=True, choices=[('Swarm', 'Swarm Checkin'), ('Datetime', 'Time & Date'), ('Request', 'Requested Moment')], max_length=8, verbose_name='The event that should trigger delivery of the Moment.')),
                ('details', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
